# 启动端口
spring:
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://49.232.21.180:3306/abutment?useUnicode=true&zeroDateTimeBehavior=round&characterEncoding=UTF-8
    username: root
    password: 146118
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 49.232.21.180
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379

server:
  port: 9527


#rsa加密配置
rsa:
  encrypt:
    debug: false
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDWVoGPPxAYp9A3R7sX1gZFVMm13AUIfn5gYBv8/lfn9RrzXqux6kDrh8ysvKRjd0YSqE3hYPgK0JLy7eweV4AcsuRKmDaXf/NUgCQbmCXQM7UfMZvwed4FKoYNnvbixwq8AV+HQQjGLip8FUDlizES8GRN7pEODbB+rruToRiGNQIDAQAB
    #      -----END PUBLIC KEY-----
    privateKey: MIICeQIBADANBgkqhkiG9w0BAQEFAASCAmMwggJfAgEAAoGBANZWgY8/EBin0DdH
      uxfWBkVUybXcBQh+fmBgG/z+V+f1GvNeq7HqQOuHzKy8pGN3RhKoTeFg+ArQkvLt
      7B5XgByy5EqYNpd/81SAJBuYJdAztR8xm/B53gUqhg2e9uLHCrwBX4dBCMYuKnwV
      QOWLMRLwZE3ukQ4NsH6uu5OhGIY1AgMBAAECgYEAuitRRXblKEU6mYl4fG+t6rKG
      sat1w7b7VgKkzM6u1A8VZaYpQ9PQp8PAh5kiwDJtbu85FjX/vIUF3nPBz2j5IFvP
      sJrSVJkJ0hzRs/cWYeby5W3LsN4+hJNbYbPtLYJOLmGIlBJuLP3pTWQas8MfrKKN
      QfQFUjZ2btICxvn2o4ECQQD/1pq2lcZzCIu0H53s0C9CdGQtDrN/OrIHBgDnhDuW
      xxjXF9teHC4An9L0/Ofc0JGyXSq8ErNmPlbeEfy4R1ddAkEA1nkv0zlPpCOPpv9J
      4CzhHuxOk909p2f3ehAeNHUu3PWCLL/GrSUwq10ZEIr5yY+MAfRWOdqy9moOBFr5
      O8G0uQJBAKSUuhKbZ365EKZfcIjXpI9rsMYLnw1KBRzfj9VgC7WDf0df4Y85MZ7V
      MjDIQaCbzB6iMMusfBxaHifeCmXB/0ECQQDRpXhoYrdE3TYIqbdPGM+d6KQOyc8A
      mxJAEQ1Vfc6nUp1CnNvaWGYwvDpJ/2+X5WeYaXz35J3XXWgCPeMu1HSRAkEAgmhx
      rwShZsjCeE+Pyqg5Wh/a/r2+Ek68m1B+GSnoR58kLv+lhIKnc6baRaHQJJdrtAzH
      BlZVJ5JhfNVgQGCuJQ==

# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico

# Mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:**/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl